name: Sync multiple branches

concurrency: catalog-test

on:
  push:
    branches:
      - 'staging'
  workflow_dispatch:

jobs:
  test-and-sync:
    name: Test and Sync SCALE Catalog
    runs-on: actions-runner-large
    steps:
          
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        name: Checkout
        with:
          token: ${{ secrets.BOT_TOKEN }}
          
      - name: catalog tests
        shell: bash
        run: |
          echo "Starting Catalog Validation"
          python3 /catalog_validation/catalog_validation/scripts/catalog_validate.py validate --path "${PWD}" --ignore-catalog-json

      - name: catalog json generation
        shell: bash
        run: |
          echo "Starting Catalog json Generation"
          python3 /catalog_validation/catalog_validation/scripts/catalog_update.py update --path "${PWD}"

      - name: Merge staging into main
        shell: bash
        run: |
          cd "${PWD}"
          git config user.name "TrueCharts-Bot"
          git config user.email "bot@truecharts.org"
          git add catalog.json || echo "Adding catalog.json failed"
          git add **/app_versions.json || echo "Adding app_version.json files failed"
          git commit --all -m "Commit app_versions.json and catalog.json" || echo "Commiting app_versions.json and catalog.json failed"
          git push -f origin staging:main
